src/main/java/pers/corvey/exam/entity/common/BaseComment.java
package pers.corvey.exam.entity.common;

import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.MappedSuperclass;

import pers.corvey.exam.entity.sys.SysUser;

@MappedSuperclass
public class BaseComment extends BaseEntityImpl<Long> {
	
	private SysUser user;
	private String content;
	private Integer good = 0;
	
	@ManyToOne(fetch=FetchType.EAGER)
	public SysUser getUser() {
		return user;
	}
	public void setUser(SysUser user) {
		this.user = user;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public Integer getGood() {
		return good;
	}
	public void setGood(Integer good) {
		this.good = good;
	}
}

src/main/java/pers/corvey/exam/entity/common/BaseEntity.java
package pers.corvey.exam.entity.common;

import java.io.Serializable;
import java.util.Date;

import pers.corvey.exam.entity.sys.SysUser;
import pers.corvey.exam.util.CurrentUtils;

public interface BaseEntity<ID extends Serializable> extends IdEntity<ID> {
	
	SysModifyLog getSysModifyLog();
	void setSysModifyLog(SysModifyLog sysModifyLog);
	
	/**
	 * 更新修改记录
	 * @param entity
	 */
	default void updateSysModifyLog() {
		SysUser currentUser = CurrentUtils.getCurrentUser();
		Date nowDate = new Date();
		SysModifyLog modifyLog = getSysModifyLog();
		if (modifyLog == null) {	// modifyLog为空，即新增操作
			modifyLog = new SysModifyLog();
			modifyLog.setCreateDate(nowDate);
			modifyLog.setCreator(currentUser);
			setSysModifyLog(modifyLog);
		} else {	// modifyLog不为空，即更新操作
			modifyLog.setModifiedDate(nowDate);
			modifyLog.setModifier(currentUser);
		}
	}
}

src/main/java/pers/corvey/exam/entity/common/BaseEntityImpl.java
package pers.corvey.exam.entity.common;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;


/**
 * 注意：子类必须要有空的构造方法 
 * @author Corvey
 * @param <ID>
 */
@MappedSuperclass
public abstract class BaseEntityImpl<ID extends Serializable> implements BaseEntity<ID> {

	private static final long serialVersionUID = -290755885790882631L;
	
	protected ID id;
	protected SysModifyLog sysModifyLog;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Override
	public ID getId() {
		return id;
	}
	
	@Override
	public void setId(ID id) {
		this.id = id;
	}

	@OneToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
	@Override
	public SysModifyLog getSysModifyLog() {
		return sysModifyLog;
	}
	
	@Override
	public void setSysModifyLog(SysModifyLog sysModifyLog) {
		this.sysModifyLog = sysModifyLog;
	}
}

src/main/java/pers/corvey/exam/entity/common/IdEntity.java
package pers.corvey.exam.entity.common;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public interface IdEntity<ID extends Serializable> extends Serializable {
	
	ID getId();
	void setId(ID id);
	
	static <T extends Serializable> List<T> getCollectionIds(Iterable<? extends IdEntity<T>> entities) {
		List<T> ids = new ArrayList<>();
		if (entities != null) {
			entities.forEach(e -> ids.add(e.getId()));
		}
		return ids;
	}
}

src/main/java/pers/corvey/exam/entity/common/SysModifyLog.java
package pers.corvey.exam.entity.common;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import org.hibernate.annotations.GenericGenerator;

import pers.corvey.exam.entity.sys.SysUser;

@Entity
public class SysModifyLog implements IdEntity<String> {
	
	private static final long serialVersionUID = 6146093577543710236L;
	
	private String id;
	private SysUser creator;
	private Date createDate;
	private SysUser modifier;
	private Date modifiedDate;
	
	public SysModifyLog() {}
	
	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(columnDefinition = "char(32)")
	@Override
	public String getId() {
		return id;
	}
	
	@Override
	public void setId(String id) {
		this.id = id;
	}
	
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "creator_user_id", updatable = false)
	public SysUser getCreator() {
		return creator;
	}
	
	public void setCreator(SysUser creator) {
		this.creator = creator;
	}
	
	@Column(updatable = false)
	public Date getCreateDate() {
		return createDate == null ? new Date() : createDate;
	}
	
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "modifier_user_id")
	public SysUser getModifier() {
		return modifier;
	}
	
	public void setModifier(SysUser modifier) {
		this.modifier = modifier;
	}
	
	public Date getModifiedDate() {
		return modifiedDate;
	}
	
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	
	@Override
	public String toString() {
		return String.format("SysModifyLog[id=%s, create_date=%s, create_id=%s, modify_date=%s, modify_id=%s]", id, createDate, creator, modifiedDate, modifier);
	}
}

src/main/java/pers/corvey/exam/entity/sys/SysUser.java
package pers.corvey.exam.entity.sys;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Transient;

import org.springframework.security.core.userdetails.UserDetails;

import pers.corvey.exam.entity.common.BaseEntityImpl;
import pers.corvey.exam.entity.common.IdEntity;

@Entity
public class SysUser extends BaseEntityImpl<Long> implements UserDetails {

	private static final long serialVersionUID = -8934005291821318128L;
	private String name;
	private String username;
	private String password;
	private Integer money;
	private Set<SysAuthority> authorities;
	
	public SysUser() {}
	
	@Override
	public String toString() {
		return String.format("SysUser[id=%s, name=%s, username=%s, password=%s]", 
				id, name, username, password);
	}
	
	@Column(length = 20, nullable = false)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	@Column(length = 20, updatable = false, nullable = false, unique = true)
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	
	@Override
	@Column(columnDefinition = "char(32)", nullable = false)
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	
	public Integer getMoney() {
		return money;
	}

	public void setMoney(Integer money) {
		this.money = money;
	}
	
	@Override
	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name = "sys_user_authority")
	public Set<SysAuthority> getAuthorities() {
		return authorities;
	}
	
	public void setAuthorities(Set<SysAuthority> authorities) {
		this.authorities = authorities;
	}

	@Override
	@Transient
	public boolean isAccountNonExpired() {
		return true;
	}
	
	@Override
	@Transient
	public boolean isAccountNonLocked() {
		return true;
	}
	
	@Override
	@Transient
	public boolean isCredentialsNonExpired() {
		return true;
	}
	
	@Override
	@Transient
	public boolean isEnabled() {
		return true;
	}
	
	/*----------JSP需要用到的方法--------------*/
	
	@Transient
	public Boolean getAdmin() {
		return authorities.stream()
				.map(x -> x.getAuthority())
				.anyMatch(a -> a.equals("ROLE_ADMIN"));
	}
	
	@Transient
	public List<Byte> getAuthorityIds() {
		return IdEntity.getCollectionIds(getAuthorities());
	}
	
	@Transient
	public String getAuthorityNames() {
		if (authorities == null) {
			return null;
		}
		List<String> names = authorities.stream()
				.sorted((a, b) -> a.getId() < b.getId() ? -1 : 1)
				.map(x -> x.getAuthority().replace("ROLE_", ""))
				.collect(Collectors.toList());
		return String.join(", ", names);
	}
}

src/main/java/pers/corvey/exam/controller/common/BaseController.java
package pers.corvey.exam.controller.common;

import java.io.Serializable;

import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import pers.corvey.exam.entity.common.BaseEntity;

public interface BaseController<T extends BaseEntity<ID>, ID extends Serializable> {

	/**
	 * 列表页面地址
	 */
	String LIST_PATH = "/list";
	
	/**
	 * 详细信息页面地址 
	 */
	String DETAIL_PATH = "/detail";
	
	/**
	 * 新增或修改页面地址 
	 */
	String INPUT_PATH = "/input";
	
	/**
	 * 删除地址 
	 */
	String DELETE_PATH = "/delete";
	
	/**
	 * 保存地址 
	 */
	String SAVE_PATH = "/save";
	
	/**
	 * 显示列表页面
	 * @param model
	 * @return
	 */
	@RequestMapping(LIST_PATH)
	String showListView(Model model);
	
	/**
	 * 显示详细信息页面
	 * @param id
	 * @param model
	 * @return
	 */
	@RequestMapping(DETAIL_PATH)
	String showDetailView(Model model, T entity);
	
	/**
	 * 显示新增或修改信息页面
	 * @param id
	 * @param model
	 * @return
	 */
	@RequestMapping(INPUT_PATH)
	String showInputView(Model model, T entity);
	
	/**
	 * 通过id删除实体
	 * @param id
	 * @return
	 */
	@RequestMapping(DELETE_PATH)
	String deleteById(ID id);
	
}

src/main/webapp/common/head.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>

<meta charset="utf-8">
<script type="text/javascript" src="${ctx}/static/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="${ctx}/static/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="${ctx}/static/css/bootstrap.min.css" />
<link rel="stylesheet" href="${ctx}/static/css/my-css.css" />
<script type="text/javascript" src="${ctx}/static/js/my-js.js"></script>

<title>在线考试系统</title>

src/main/webapp/common/header.jsp
<%@page import="pers.corvey.exam.util.CurrentUtils"%>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	request.setAttribute("user", CurrentUtils.getCurrentUser());
%>
<div id="header">
  <nav class="navbar" id="header-navbar">
    <div class="container-fluid">
      <div class="navbar-header" style="padding-left: 15px;">
        <a class="navbar-brand" href="${ctx}/login" style="padding: 3 0 2 0;">
          <img src="${ctx}/static/img/logo.png" />
        </a>
      </div>
      <div class="pull-left" style="padding: 5px 0 5px 10px">
        <ul class="nav navbar-nav">
          <li><a href='${ctx}/exam/show'>在线考试</a></li>
          <%-- <li><a href='${ctx}/exam/show'>在线练习</a></li> --%>
          <li><a href='${ctx}/examresult/show'>我的成绩</a></li>
          <li><a href='${ctx}/exam/wrong/show'>我的错题</a></li>
          <li><a href='${ctx}/resource/all'>资源大全</a></li>
        </ul>
      </div>
      <div class="pull-right" style="padding: 5px 15px 5px 0">
        <!-- <form class="navbar-form navbar-left" id="searchForm">
          <div class="input-group" style="width: 200px;">
            <input type="text" class="form-control" placeholder="Search" id="keyword">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
            </div>
          </div>
        </form> -->
        <ul class="nav navbar-nav">
          <li><a>${user.name}</a></li>
          <li><a>积分：${user.money}</a></li>
          <c:if test="${user.admin}">
          	<li><a href="${ctx}/sys/user/list">管理员页面</a></li>
          </c:if>
          <li><a href="${ctx}/logout">退出登录</a></li>
        </ul>
      </div>
    </div>
  </nav>
</div>

src/main/webapp/common/left-bar.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>

<div class="col-xs-2 my-nav-bar">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="glyphicon glyphicon-th-list"></span>&nbsp;信息管理
      </h3>
    </div>
    <div class="list-group">
      <a class="list-group-item" href="${ctx}/sys/user/list">用户管理</a>
      <a class="list-group-item" href="${ctx}/exampaper/list">试卷管理</a>
      <a class="list-group-item" href="${ctx}/question/list">题目管理</a>
      <a class="list-group-item" href="${ctx}/resource/list">资源管理</a>
      <a class="list-group-item" href="${ctx}/exam/list">考试管理</a>
      <a class="list-group-item" href="${ctx}/examresult/list">成绩管理</a>
    </div>
  </div>
</div>

src/main/webapp/common/page.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%-- action='#' 表示提交数据到本页 --%>
<form id="mainForm" action="#" method="post" />
<input type="hidden" id="pageNo" name="pageNo" />
<input type="hidden" id="orderBy" name="orderBy" />
<input type="hidden" id="order" name="order" />
<div class="btn-group" role="group" aria-label="...">
	<c:if test="${page.totalPages > 1 && page.pageNo != 1}">
		<button class="btn btn-default" onclick="jumpPage(1)">首页</button>
	</c:if>
	<c:if test="${page.hasPre}">
	    <button class="btn btn-default" onclick="jumpPage(${page.pageNo - 1})">上一页</button>
	</c:if>
	<c:if test="${page.totalPages > 1}">
		<c:choose>
			<c:when test="${page.pageNo - 5 < 0}">
				<c:forEach var="i" begin="1" end="${page.totalPages > 10 ? 10 : page.totalPages}">
					<c:choose>
						<c:when test="${i == page.pageNo}">
							<button class="btn btn-primary">${i}</button>
						</c:when>
						<c:otherwise>
							<button class="btn btn-default" onclick="jumpPage(${i})">${i}</button>
						</c:otherwise>
					</c:choose>
				</c:forEach>
			</c:when>
			<c:when test="${page.pageNo - 5 >= 0 && (page.pageNo + 5) <= page.totalPages}">
				<c:forEach var="i" begin="${page.pageNo > 5 ? (page.pageNo - 5) : 1}" 
				    end="${page.totalPages > (page.pageNo - 5 + 9) ? (page.pageNo - 5 + 9) : page.totalPages}">
					<c:choose>
						<c:when test="${i == page.pageNo}">
							<button class="btn btn-primary">${i}</button>
						</c:when>
						<c:otherwise>
							<button class="btn btn-default" onclick="jumpPage(${i})">${i}</button>
						</c:otherwise>
					</c:choose>
				</c:forEach>
			</c:when>
			<c:when test="${page.pageNo + 5 > page.totalPages && page.pageNo - 5 >= 0}">
				<c:forEach var="i" begin="${(page.pageNo - 9) > 0 ? page.pageNo - 9 : i + 1}" end="${page.totalPages}">
					<c:choose>
						<c:when test="${i == page.pageNo}">
							<button class="btn btn-primary">${i}</button>
						</c:when>
						<c:otherwise>
							<button class="btn btn-default" onclick="jumpPage(${i})">${i}</button>
						</c:otherwise>
					</c:choose>
				</c:forEach>
			</c:when>
		</c:choose>
	</c:if>
	<c:if test="${page.hasNext}">
	    <button class="btn btn-default" onclick="jumpPage(${page.pageNo + 1})">下一页</button>
	</c:if>
	<c:if test="${page.totalPages > 1 && page.pageNo != page.totalPages}">
	    <button class="btn btn-default" onclick="jumpPage(${page.totalPages})">尾页</button>
	</c:if>

	<c:if test="${page.totalPages > 8}">
		<div class="input-group">
	      <input id="gopage" name="gopage" class="form-control" style="width:25px;" value="${page.pageNo}"
	           type="number" min="1" max="${page.totalPages}"/>
	      <span class="input-group-btn">
	        <button class="btn btn-default" onclick="jumpPage($('#gopage').val())">跳转</button>
	      </span>
	    </div>
	</c:if>

</div>

src/main/webapp/common/show-message.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>

<c:if test="${message != null}">
  <div class="alert alert-dismissable ${message.cssClass}">
    <button type="button" class="close" data-dismiss="alert"aria-hidden="true">
      &times;
    </button>
    <c:out value="${message.text}" />
  </div>
</c:if>
<%session.removeAttribute("message");%>

src/main/webapp/common/taglibs.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%-- 标签 --%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<c:set var="ctx" value="${pageContext.request.contextPath}"/>