src/main/java/pers/corvey/exam/entity/sys/SysAuthority.java
package pers.corvey.exam.entity.sys;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.springframework.security.core.GrantedAuthority;

import pers.corvey.exam.entity.common.IdEntity;

@Entity
public class SysAuthority implements GrantedAuthority, IdEntity<Byte> {
	
	private static final long serialVersionUID = -59397517996869520L;
	
	private Byte id;
	private String authority;
	
	public SysAuthority() {}
	
	@Override
	public String toString() {
		return String.format("SysAuthority[id=%d, authority=%s]", id, authority);
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Override
	public Byte getId() {
		return id;
	}

	@Override
	public void setId(Byte id) {
		this.id = id;
	}
	
	@Override
	@Column(length = 20, unique = true)
	public String getAuthority() {
		return authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}
}

src/main/java/pers/corvey/exam/entity/sys/SysUser.java
package pers.corvey.exam.entity.sys;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Transient;

import org.springframework.security.core.userdetails.UserDetails;

import pers.corvey.exam.entity.common.BaseEntityImpl;
import pers.corvey.exam.entity.common.IdEntity;

@Entity
public class SysUser extends BaseEntityImpl<Long> implements UserDetails {

	private static final long serialVersionUID = -8934005291821318128L;
	private String name;
	private String username;
	private String password;
	private Integer money;
	private Set<SysAuthority> authorities;
	
	public SysUser() {}
	
	@Override
	public String toString() {
		return String.format("SysUser[id=%s, name=%s, username=%s, password=%s]", 
				id, name, username, password);
	}
	
	@Column(length = 20, nullable = false)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	@Column(length = 20, updatable = false, nullable = false, unique = true)
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	
	@Override
	@Column(columnDefinition = "char(32)", nullable = false)
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	
	public Integer getMoney() {
		return money;
	}

	public void setMoney(Integer money) {
		this.money = money;
	}
	
	@Override
	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name = "sys_user_authority")
	public Set<SysAuthority> getAuthorities() {
		return authorities;
	}
	
	public void setAuthorities(Set<SysAuthority> authorities) {
		this.authorities = authorities;
	}

	@Override
	@Transient
	public boolean isAccountNonExpired() {
		return true;
	}
	
	@Override
	@Transient
	public boolean isAccountNonLocked() {
		return true;
	}
	
	@Override
	@Transient
	public boolean isCredentialsNonExpired() {
		return true;
	}
	
	@Override
	@Transient
	public boolean isEnabled() {
		return true;
	}
	
	/*----------JSP需要用到的方法--------------*/
	
	@Transient
	public Boolean getAdmin() {
		return authorities.stream()
				.map(x -> x.getAuthority())
				.anyMatch(a -> a.equals("ROLE_ADMIN"));
	}
	
	@Transient
	public List<Byte> getAuthorityIds() {
		return IdEntity.getCollectionIds(getAuthorities());
	}
	
	@Transient
	public String getAuthorityNames() {
		if (authorities == null) {
			return null;
		}
		List<String> names = authorities.stream()
				.sorted((a, b) -> a.getId() < b.getId() ? -1 : 1)
				.map(x -> x.getAuthority().replace("ROLE_", ""))
				.collect(Collectors.toList());
		return String.join(", ", names);
	}
}

src/main/java/pers/corvey/exam/controller/sys/CaptchaController.java
package pers.corvey.exam.controller.sys;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Objects;

import javax.imageio.ImageIO;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import pers.corvey.exam.util.CaptchaUtils;



@Controller
@RequestMapping("/captcha")
public class CaptchaController {

    public static final String CAPTCHA_ATTRIBUTE_NAME = "captcha";
    
    @GetMapping
    public void createCaptcha(HttpSession session, HttpServletResponse response) {
        String captchaCode = CaptchaUtils.createCaptcha();
        session.setAttribute(CAPTCHA_ATTRIBUTE_NAME, captchaCode);
        
        response.setContentType("image/png");
        response.setHeader("Cache-Control", "no-cache, no-store");
        response.setHeader("Pragma", "no-cache");
        response.setDateHeader("expries", -1);
        
        BufferedImage image = CaptchaUtils.createCaptchaImage(captchaCode);
        try {
            ServletOutputStream out = response.getOutputStream();
            ImageIO.write(image, "png", out);
            out.flush();
            out.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static boolean judge(HttpServletRequest request) {
    	HttpSession session = request.getSession();
    	String inputCode = request.getParameter(CAPTCHA_ATTRIBUTE_NAME);
    	String correctCode = (String) session.getAttribute(CAPTCHA_ATTRIBUTE_NAME);
    	session.removeAttribute(CAPTCHA_ATTRIBUTE_NAME);
    	if (inputCode == null || correctCode == null) {
    		return false;
    	}
    	return Objects.equals(inputCode.toLowerCase(), correctCode.toLowerCase());
    }
}

src/main/java/pers/corvey/exam/controller/sys/ExceptionController.java
package pers.corvey.exam.controller.sys;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping("/exception")
public class ExceptionController {

	@GetMapping("/403")
	public String show403Page() {
		return "exception/403";
	}
}

src/main/java/pers/corvey/exam/controller/sys/SysUserController.java
package pers.corvey.exam.controller.sys;

import java.util.List;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import pers.corvey.exam.controller.common.BaseControllerImpl;
import pers.corvey.exam.entity.sys.SysAuthority;
import pers.corvey.exam.entity.sys.SysUser;
import pers.corvey.exam.service.sys.SysAuthorityService;
import pers.corvey.exam.service.sys.SysUserService;

@Controller
@RequestMapping("/sys/user")
public class SysUserController extends BaseControllerImpl<SysUser, Long> {

	private final SysUserService sysUserService;
	
	private final SysAuthorityService sysAuthorityService;
	
	@Autowired
	public SysUserController(SysUserService sysUserService, 
			SysAuthorityService sysAuthorityService) {
		
		super(sysUserService, "sys/user-input.jsp", "sys/user-list.jsp");
		this.sysUserService = sysUserService;
		this.sysAuthorityService = sysAuthorityService;
	}
	
	/**
	 * 保存记录
	 * @param user
	 * @param ids
	 * @return
	 */
	@PostMapping(SAVE_PATH)
	public String save(@ModelAttribute("entity") SysUser user,
			@RequestParam(name="authorityIds", required=false) List<Byte> authorityIds) {
		if (user.getMoney() == null) {
			user.setMoney(1000);
		}
		Set<SysAuthority> authorities = sysAuthorityService.findAll(authorityIds);
		authorities.add(sysAuthorityService.getDefaultAuthority());
		user.setAuthorities(authorities);
		return baseSave(user);
	}
	
	@PostMapping("/search")
	public String search(Model model, @RequestParam("keyword") String keyword) {
		return baseShowListView(model, sysUserService.search(keyword));
	}
	
	@Override
	public String showInputView(Model model, @ModelAttribute("entity") SysUser entity) {
		Iterable<SysAuthority> authorities = sysAuthorityService.findAll();
		model.addAttribute("authorities", authorities);
		return super.showInputView(model, entity);
	}
	
	@Override
	public String showDetailView(Model model, @ModelAttribute("entity") SysUser entity) {
		Iterable<SysAuthority> authorities = sysAuthorityService.findAll();
		model.addAttribute("authorities", authorities);
		return super.showDetailView(model, entity);
	}
}

src/main/webapp/WEB-INF/views/sys/exampaper-list.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@include file="/common/taglibs.jsp"%>

<div class="col-xs-10">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="glyphicon glyphicon-align-justify"></span>
        &nbsp;试卷信息管理
      </h3>
    </div>
    <div class="panel-body">
	    <%@include file="/common/show-message.jsp" %>
	    <div>
	      <a class="btn btn-primary pull-left" href="${ctx}/exampaper/input">新增</a>
	      <!-- 暂时装饰用 -->

	    </div>
		<table class="table table-bordered">
      	<tr>
      	  <th>试卷名称</th>
      	  <th>试卷描述</th>
      	  <th>出题人</th>
      	  <th>操作</th>
      	</tr>
		<c:forEach items="${entities}" var="exampaper">
		  <tr>
			<td><c:out value="${exampaper.name}" /></td>
			<td><c:out value="${exampaper.description}" /></td>
			<td><c:out value="${exampaper.sysModifyLog.creator.name}"/></td>
			<td>
			  <a class="btn btn-info btn-sm" href="${ctx}/exampaper/detail?id=${exampaper.id}">查看</a>
			  <a class="btn btn-warning btn-sm" href="${ctx}/exampaper/input?id=${exampaper.id}">修改</a>
			  <a class="btn btn-danger btn-sm" href="${ctx}/exampaper/delete?id=${exampaper.id}">删除</a>
			</td>
		  </tr>
		</c:forEach>
	  </table>
    </div>
  </div>
</div>

src/main/webapp/WEB-INF/views/sys/user-input.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@include file="/common/taglibs.jsp"%>

<div class="col-xs-10">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="glyphicon glyphicon-align-justify"></span> &nbsp;用户信息管理
      </h3>
    </div>
    <div class="panel-body">
      <form:form action="${ctx}/sys/user/save" method="post"
        cssClass="form-horizontal" modelAttribute="entity">
        <form:hidden path="id" />
        <div class="form-group">
          <label for="username" class="col-sm-2 control-label"> 用户名 </label>
          <div class="col-sm-4">
            <form:input cssClass="form-control" path="username"
              disabled="${entity.id != null}" />
          </div>
        </div>
        <div class="form-group">
          <label for="password" class="col-sm-2 control-label">密码</label>
          <div class="col-sm-4">
            <form:password cssClass="form-control" path="password" />
          </div>
        </div>
        <div class="form-group">
          <label for="name" class="col-sm-2 control-label">姓名</label>
          <div class="col-sm-4">
            <form:input cssClass="form-control" path="name" />
          </div>
        </div>
        <div class="form-group">
          <label for="name" class="col-sm-2 control-label">权限角色</label>
          <div class="col-sm-4">
            <form:checkboxes path="authorityIds" delimiter="<br/>"
              items="${authorities}" itemLabel="authority" itemValue="id" />
          </div>
        </div>
        <div class="col-md-8 text-center">
          <button class="btn btn-primary" type="submit">提交</button>
          &emsp;&emsp;&emsp;&emsp;
          <a class="btn btn-warning" href="${ctx}/sys/user/list">返回</a>
        </div>
      </form:form>
    </div>
  </div>
</div>

src/main/webapp/WEB-INF/views/sys/user-list.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@include file="/common/taglibs.jsp"%>

<div class="col-xs-10">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="glyphicon glyphicon-align-justify"></span>
        &nbsp;用户信息管理
      </h3>
    </div>
    <div class="panel-body">
	    <%@include file="/common/show-message.jsp" %>
	    <div>
	      <a class="btn btn-primary pull-left" href="${ctx}/sys/user/input">新增</a>

	    </div>
		<table class="table table-bordered">
      	<tr>
      	  <th>昵称</th>
      	  <th>用户名</th>
      	  <th>用户角色</th>
      	  <th>操作</th>
      	</tr>
		<c:forEach items="${entities}" var="user">
		  <tr>
			<td><c:out value="${user.name}" /></td>
			<td><c:out value="${user.username}" /></td>
			<td><c:out value="${user.authorityNames}"/></td>
			<td>
			  <a class="btn btn-info btn-sm" href="${ctx}/sys/user/detail?id=${user.id}">查看</a>
			  <a class="btn btn-warning btn-sm" href="${ctx}/sys/user/input?id=${user.id}">修改</a>
			  <a class="btn btn-danger btn-sm" href="${ctx}/sys/user/delete?id=${user.id}">删除</a>
			</td>
		  </tr>
		</c:forEach>
	  </table>
    </div>
  </div>
</div>